name: CenterNetROINoGlobal

defaults:
  - img_aug: translation_aug.yaml
  - img_aug@bbox_aug: bbox_color_jitter.yaml
  - img_aug@eye_aug: img_color_jitter.yaml
  - encoder: resnet_conv.yaml
  - bbox_norm: default.yaml
  - bbox_position: bbox_position_embedding.yaml
  - pooling: roi_align_spatialsoftmax.yaml
  - spatial_projection: spatial_projection.yaml
  - projection: linear_projection.yaml
  - decoder: centernet_gmm_transformer_action_token.yaml
