name: GTGMMTransformerPolicySpatialContext3D

defaults:
  - img_aug: translation_aug.yaml
  - encoder: resnet_conv.yaml
  - bbox_norm: rel_3d_pos_aug.yaml
  - bbox_position: rel_3d_position_embedding.yaml
  - pooling: roi_align_spatialsoftmax.yaml
  - spatial_projection: spatial_projection.yaml
  - projection: linear_projection.yaml
  - decoder: centernet_gmm_transformer_spatial_context.yaml
